# Generated by Django 2.2.2 on 2019-07-10 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 10, 13, 13, 35, 481268, tzinfo=utc)),
        ),
    ]
